// <auto-generated />
using System;
using AHuiHou.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AHuiHou.Infrastructure.Migrations
{
    [DbContext(typeof(AHuiHouDbContext))]
    [Migration("20260525172440_DecimalPointsAndColombianSeed")]
    partial class DecimalPointsAndColombianSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AHuiHou.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsQuietZone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsQuietZone = false,
                            Name = "Piso 1"
                        },
                        new
                        {
                            Id = 2,
                            IsQuietZone = false,
                            Name = "Terraza"
                        },
                        new
                        {
                            Id = 3,
                            IsQuietZone = true,
                            Name = "Sala Silenciosa"
                        });
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Café de especialidad, tés, frappés y más",
                            Name = "Bebidas"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sándwiches artesanales, repostería y bowls",
                            Name = "Comida"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Planes de acceso a espacios de trabajo",
                            Name = "Coworking"
                        });
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.LoyaltyWallet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId");

                    b.ToTable("loyalty_wallets", (string)null);
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.MembershipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("membership_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountRate = 15.00m,
                            MonthlyFee = 149900m,
                            Name = "VIP"
                        },
                        new
                        {
                            Id = 2,
                            DiscountRate = 10.00m,
                            MonthlyFee = 89900m,
                            Name = "Diamante"
                        },
                        new
                        {
                            Id = 3,
                            DiscountRate = 5.00m,
                            MonthlyFee = 39900m,
                            Name = "Estudiante"
                        });
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.PointTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("point_transactions", (string)null);
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PointsAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Espresso",
                            PointsAwarded = 0,
                            Price = 5500m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Cappuccino",
                            PointsAwarded = 0,
                            Price = 7500m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Latte Macchiato",
                            PointsAwarded = 0,
                            Price = 9000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Americano",
                            PointsAwarded = 0,
                            Price = 5000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Prensa Francesa",
                            PointsAwarded = 0,
                            Price = 8500m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Mocaccino",
                            PointsAwarded = 0,
                            Price = 9500m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "Té Chai Latte",
                            PointsAwarded = 0,
                            Price = 8000m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Name = "Cold Brew",
                            PointsAwarded = 0,
                            Price = 10000m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Name = "Frappé de Café",
                            PointsAwarded = 0,
                            Price = 12500m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Name = "Matcha Latte",
                            PointsAwarded = 0,
                            Price = 11000m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Croissant Artesanal",
                            PointsAwarded = 0,
                            Price = 7000m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Name = "Torta de Almojábana",
                            PointsAwarded = 0,
                            Price = 8500m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Name = "Sándwich de Pollo",
                            PointsAwarded = 0,
                            Price = 18000m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Name = "Sándwich Artesanal",
                            PointsAwarded = 0,
                            Price = 20000m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Name = "Bagel con Salmón",
                            PointsAwarded = 0,
                            Price = 22000m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Name = "Ensalada César",
                            PointsAwarded = 0,
                            Price = 16500m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Name = "Bowl de Frutas",
                            PointsAwarded = 0,
                            Price = 15000m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Name = "Pastel de Chocolate",
                            PointsAwarded = 0,
                            Price = 12000m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Name = "Coworking - Hora",
                            PointsAwarded = 0,
                            Price = 8000m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Name = "Coworking - Medio Día",
                            PointsAwarded = 0,
                            Price = 25000m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Name = "Coworking - Día Completo",
                            PointsAwarded = 0,
                            Price = 45000m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Name = "Coworking - Semana",
                            PointsAwarded = 0,
                            Price = 180000m
                        });
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DiscountCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("promotions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Café Americano + Croissant artesanal por solo $10.000. Válido hasta las 11am.",
                            DiscountCode = "DESAYUNO10K",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
                            IsActive = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Combo Desayuno"
                        },
                        new
                        {
                            Id = 2,
                            Description = "2x1 en Cappuccinos de 4pm a 6pm. Trae a tu colega y solo pagas uno.",
                            DiscountCode = "AFTER2X1",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800",
                            IsActive = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "After Office 2x1"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Todos los lunes, 20% de descuento en cualquier latte. Tu semana empieza mejor.",
                            DiscountCode = "LUNESLATTE",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800",
                            IsActive = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Lunes de Latte"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Día completo de coworking por solo $35.000 (antes $45.000). Café ilimitado incluido.",
                            DiscountCode = "COWORK35K",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
                            IsActive = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Pase Coworking Día"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Regístrate y recibe un espresso o americano de bienvenida totalmente gratis.",
                            DiscountCode = "BIENVENIDO",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
                            IsActive = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Primer Café Gratis"
                        },
                        new
                        {
                            Id = 6,
                            Description = "30% de descuento en planes de coworking con carnet vigente. WiFi + café ilimitado.",
                            DiscountCode = "ESTUDIANTE30",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800",
                            IsActive = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Plan Estudiante"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Cualquier té + pastry a mitad de precio de 3pm a 5pm. La hora del té perfecta.",
                            DiscountCode = "TEATIME50",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800",
                            IsActive = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Té + Pastelería 50% Off"
                        },
                        new
                        {
                            Id = 8,
                            Description = "4 horas de coworking en sala privada + 4 cafés por solo $80.000. Ideal para brainstorms.",
                            DiscountCode = "TEAM80K",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800",
                            IsActive = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sala para Equipos"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Cada sábado, prueba un café de origen colombiano con 15% de descuento. Conoce nuestro café.",
                            DiscountCode = "SABADO15",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800",
                            IsActive = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sábados de Origen Único"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Trae a un amigo nuevo y ambos ganan 100 puntos de lealtad extra en su primera compra.",
                            DiscountCode = "AMIGO100",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=800",
                            IsActive = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Amigo Referido"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Jueves: toma un libro de nuestra biblioteca y recibe un espresso cortesía. Lectura + café.",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1513475382585-d06e58bc1ae2?w=800",
                            IsActive = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Café & Libro"
                        },
                        new
                        {
                            Id = 12,
                            Description = "3 piezas de pastelería + 2 americanos por solo $22.000. Perfecto para compartir.",
                            DiscountCode = "PASTRY22K",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=800",
                            IsActive = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Pack Repostería x3"
                        });
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TableId", "StartTime", "EndTime");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<bool>("HasOutlet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("tables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            Capacity = 2,
                            HasOutlet = true,
                            TableNumber = "A1"
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 1,
                            Capacity = 4,
                            HasOutlet = true,
                            TableNumber = "A2"
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 1,
                            Capacity = 2,
                            HasOutlet = false,
                            TableNumber = "A3"
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 2,
                            Capacity = 6,
                            HasOutlet = true,
                            TableNumber = "T1"
                        },
                        new
                        {
                            Id = 5,
                            AreaId = 2,
                            Capacity = 4,
                            HasOutlet = false,
                            TableNumber = "T2"
                        },
                        new
                        {
                            Id = 6,
                            AreaId = 3,
                            Capacity = 1,
                            HasOutlet = true,
                            TableNumber = "S1"
                        },
                        new
                        {
                            Id = 7,
                            AreaId = 3,
                            Capacity = 2,
                            HasOutlet = true,
                            TableNumber = "S2"
                        });
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.UserMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MembershipTypeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MembershipTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("user_memberships", (string)null);
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.LoyaltyWallet", b =>
                {
                    b.HasOne("AHuiHou.Domain.Entities.User", "User")
                        .WithOne("LoyaltyWallet")
                        .HasForeignKey("AHuiHou.Domain.Entities.LoyaltyWallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.PointTransaction", b =>
                {
                    b.HasOne("AHuiHou.Domain.Entities.User", null)
                        .WithMany("PointTransactions")
                        .HasForeignKey("UserId");

                    b.HasOne("AHuiHou.Domain.Entities.LoyaltyWallet", "Wallet")
                        .WithMany("PointTransactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Product", b =>
                {
                    b.HasOne("AHuiHou.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("AHuiHou.Domain.Entities.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AHuiHou.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Table", b =>
                {
                    b.HasOne("AHuiHou.Domain.Entities.Area", "Area")
                        .WithMany("Tables")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.UserMembership", b =>
                {
                    b.HasOne("AHuiHou.Domain.Entities.MembershipType", "MembershipType")
                        .WithMany("UserMemberships")
                        .HasForeignKey("MembershipTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AHuiHou.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Area", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.LoyaltyWallet", b =>
                {
                    b.Navigation("PointTransactions");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.MembershipType", b =>
                {
                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Table", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.User", b =>
                {
                    b.Navigation("LoyaltyWallet");

                    b.Navigation("Memberships");

                    b.Navigation("PointTransactions");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
