// <auto-generated />
using System;
using AHuiHou.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AHuiHou.Infrastructure.Migrations
{
    [DbContext(typeof(AHuiHouDbContext))]
    [Migration("20260525163103_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AHuiHou.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsQuietZone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsQuietZone = false,
                            Name = "Piso 1"
                        },
                        new
                        {
                            Id = 2,
                            IsQuietZone = false,
                            Name = "Terraza"
                        },
                        new
                        {
                            Id = 3,
                            IsQuietZone = true,
                            Name = "Sala Silenciosa"
                        });
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Café, té, smoothies y más",
                            Name = "Bebidas"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sándwiches, pasteles y snacks",
                            Name = "Comida"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Acceso a espacios de trabajo",
                            Name = "Coworking"
                        });
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.LoyaltyWallet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId");

                    b.ToTable("loyalty_wallets", (string)null);
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.MembershipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("membership_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountRate = 15.00m,
                            MonthlyFee = 99.99m,
                            Name = "VIP"
                        },
                        new
                        {
                            Id = 2,
                            DiscountRate = 10.00m,
                            MonthlyFee = 59.99m,
                            Name = "Diamante"
                        },
                        new
                        {
                            Id = 3,
                            DiscountRate = 5.00m,
                            MonthlyFee = 29.99m,
                            Name = "Estudiante"
                        });
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.PointTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("point_transactions", (string)null);
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PointsAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Espresso",
                            PointsAwarded = 0,
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Cappuccino",
                            PointsAwarded = 0,
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Latte Macchiato",
                            PointsAwarded = 0,
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Sándwich de Pollo",
                            PointsAwarded = 0,
                            Price = 8.50m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Croissant",
                            PointsAwarded = 0,
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Coworking - Hora",
                            PointsAwarded = 0,
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Coworking - Día",
                            PointsAwarded = 0,
                            Price = 25.00m
                        });
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DiscountCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("promotions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Café + Croissant por $6.00",
                            DiscountCode = "DESAYUNO6",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600",
                            IsActive = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Combo Desayuno"
                        },
                        new
                        {
                            Id = 2,
                            Description = "2x1 en Cappuccinos (4pm - 6pm)",
                            DiscountCode = "AFTER2X1",
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600",
                            IsActive = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "After Office"
                        });
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TableId", "StartTime", "EndTime");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<bool>("HasOutlet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("tables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            Capacity = 2,
                            HasOutlet = true,
                            TableNumber = "A1"
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 1,
                            Capacity = 4,
                            HasOutlet = true,
                            TableNumber = "A2"
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 1,
                            Capacity = 2,
                            HasOutlet = false,
                            TableNumber = "A3"
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 2,
                            Capacity = 6,
                            HasOutlet = true,
                            TableNumber = "T1"
                        },
                        new
                        {
                            Id = 5,
                            AreaId = 2,
                            Capacity = 4,
                            HasOutlet = false,
                            TableNumber = "T2"
                        },
                        new
                        {
                            Id = 6,
                            AreaId = 3,
                            Capacity = 1,
                            HasOutlet = true,
                            TableNumber = "S1"
                        },
                        new
                        {
                            Id = 7,
                            AreaId = 3,
                            Capacity = 2,
                            HasOutlet = true,
                            TableNumber = "S2"
                        });
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.UserMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MembershipTypeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MembershipTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("user_memberships", (string)null);
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.LoyaltyWallet", b =>
                {
                    b.HasOne("AHuiHou.Domain.Entities.User", "User")
                        .WithOne("LoyaltyWallet")
                        .HasForeignKey("AHuiHou.Domain.Entities.LoyaltyWallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.PointTransaction", b =>
                {
                    b.HasOne("AHuiHou.Domain.Entities.User", null)
                        .WithMany("PointTransactions")
                        .HasForeignKey("UserId");

                    b.HasOne("AHuiHou.Domain.Entities.LoyaltyWallet", "Wallet")
                        .WithMany("PointTransactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Product", b =>
                {
                    b.HasOne("AHuiHou.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("AHuiHou.Domain.Entities.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AHuiHou.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Table", b =>
                {
                    b.HasOne("AHuiHou.Domain.Entities.Area", "Area")
                        .WithMany("Tables")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.UserMembership", b =>
                {
                    b.HasOne("AHuiHou.Domain.Entities.MembershipType", "MembershipType")
                        .WithMany("UserMemberships")
                        .HasForeignKey("MembershipTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AHuiHou.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Area", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.LoyaltyWallet", b =>
                {
                    b.Navigation("PointTransactions");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.MembershipType", b =>
                {
                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.Table", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("AHuiHou.Domain.Entities.User", b =>
                {
                    b.Navigation("LoyaltyWallet");

                    b.Navigation("Memberships");

                    b.Navigation("PointTransactions");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
